In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df['income_cat']=pd.cut(df['median_income'], bins=[0,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5])

In [4]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index , test_index in split.split(df,df['income_cat']):
    strat_train_set=df.loc[train_index]
    strat_test_set=df.loc[test_index]

In [5]:
for sett in(strat_train_set,strat_test_set):
    sett.drop('income_cat',axis=1,inplace=True)

In [6]:
df=strat_train_set.copy()

In [7]:
housing=strat_train_set.drop('median_house_value',axis=1)
housing_labels=strat_train_set['median_house_value'].copy()

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(strategy='median')

In [10]:
housing_num=housing.select_dtypes(include=[np.number])

In [11]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [12]:
x=imputer.transform(housing_num)

In [13]:
x

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]], shape=(16512, 8))

In [14]:
housing=pd.DataFrame(x,columns=housing_num.columns,index=housing_num.index)

In [15]:
housing['ocean_proximity']=df['ocean_proximity']

In [35]:
housing=housing[['ocean_proximity']]

In [36]:
set(housing['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [37]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
ordinal_encoder=OrdinalEncoder()

In [39]:
housing_cat=ordinal_encoder.fit_transform(housing)

In [40]:
housing_cat=pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)

In [41]:
housing_cat

       ocean_proximity
12655              1.0
15502              4.0
2908               1.0
14053              4.0
20496              0.0
...                ...
15174              0.0
12661              1.0
19263              0.0
19140              0.0
19773              1.0

[16512 rows x 1 columns]

In [42]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
ordinal_encoder=OneHotEncoder()

In [44]:
housing_cat=ordinal_encoder.fit_transform(housing)

In [45]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [46]:
housing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [47]:
housing_cat=pd.DataFrame(housing_cat.toarray(),columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index=housing.index)

In [48]:
housing_cat

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]